#!/bin/bash

echo
echo "        INSTALLING APACHE LAMP SERVER WITH WORDPRESS          "
echo

echo "IMPLEMENTING APACHE2 WITH DOCUMENTATION"
sudo apt-get install apache2 apache2-bin apache2-data apache2-doc


echo "SETTING APACHE MODS WITH SSL CONFIGURATION"
sudo a2enmod ssl 
sudo a2ensite default-ssl.conf 
sudo systemctl restart apache2.service


echo "RESTARTING AND CHECKING APACHE SERVICES"
sudo netstat -tlpn
sudo systemctl enable apache2
sudo service apache2 status


echo "SETTING UP BACKEND FOR WORDPRESS"
sudo apt-get install php libapache2-mod-php php-mysql 
sudo apt search php7.2
sudo apt-get install php7.2 libapache2-mod-php7.2 php7.2-mysql php7.2-xml php7.2-gd
php -v

sudo apt install php-curl php-gd php-xml php-mbstring  php-xmlrpc php-zip php-soap php-intl

sudo rm -f /var/www/html/index.hmtl
sudo apt-get install mysql-server
sudo systemctl restart apache2

#sudo apt install php7.0-mysql mariadb-server mariadb-client

echo "MYSQL INITIALIZATION CONFIG"
sudo mysql_secure_installation

echo "INSTALLING PHPMYADMIN AND RESTARTING ALL SERVICES"
sudo systemctl restart mysql.service
sudo apt install php-gettext phpmyadmin
sudo systemctl restart apache2


mysql -u root -p -e "CREATE DATABASE WordPressDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
mysql -u root -p -e "GRANT ALL ON WordPressDB.* TO ' WordPressUser '@'localhost' IDENTIFIED BY 'NewPasswordToBeSet';"
mysql -u root -p -e "FLUSH PRIVILEGES;"

echo "CHANGE INITIAL INDEX.HTML DOC ROOT WITH INDEX.PHP THEN EXIT..."
sudo gedit /etc/apache2/mods-enabled/dir.conf

echo "PULL WORDPRESS DEV PACKAGE..."
cd /tmp && curl -O https://wordpress.org/latest.tar.gz -o wordpress.tar.gz & tar -xvzf wordpress.tar.gz & sudo mv wordpress /var/www/html
mv */wordpress/wp-config-sample.php */wordpress/wp-config.php

echo "CHANGE APACHE WP DIR PERMISSIONS"
sudo chown -R www-data:www-data /var/www/html/wordpress
sudo find /var/www/html/wordpress/ -type d -exec chmod 750 {} \;
sudo find /var/www/html/wordpress/ -type f -exec chmod 640 {} \;
curl -s https://api.wordpress.org/secret-key/1.1/salt/

sudo gedit /var/www/html/wordpress/wp-config.php

echo "Opening Wordpress Stage And PHPMyAdmin Panel On Firefox"
firefox http://localhost/wordpress
firefox http://localhost/phpmyadmin
