#!/bin/bash

sudo apt-get install apache2 apache2-bin apache2-data apache2-doc

sudo a2enmod ssl 
sudo a2ensite default-ssl.conf 
sudo systemctl restart apache2.service
sudo netstat -tlpn

sudo systemctl enable apache2

sudo apt search php7.0

sudo apt-get install php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-xml php7.0-gd

php -v

sudo rm -f /var/www/html/index.hmtl

sudo systemctl restart apache2

sudo apt install php7.0-mysql mariadb-server mariadb-client

sudo mysql_secure_installation


sudo systemctl restart mysql.service

sudo apt install php-gettext phpmyadmin

sudo systemctl restart apache2


mysql -u root -p


firefox http://localhost
firefox http://localhost/phpmyadmin
