#!/bin/bash
echo
echo "					PUSH NEW NETWORK INTERFACE TO >> /ETC/NETWORK/INTERFACES					"
echo
echo "           				     WARNING! This will modify network interfaces!      					"
echo 
echo -n "Set Hostname For Interface: "
read hostname
echo
echo -n "Set YOUR IP: "
read ip
echo
echo -n "Set DomainName (without .com): "
read domain
echo

echo "ifdown eth0; ifup eth0"
ifdown eth0; ifup eth0
echo

echo "Pushing Hostname to /etc/hostname"
echo
echo "$hostname" >> /etc/hostname
echo
echo "Pushing FQDN to /etc/hosts"
echo
echo "$ip $hostname.$domain.com" >> /etc/hosts

# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

echo "Pushing Loopback Interfaces to /etc/network/interfaces"
echo
echo "# The loopback network interface"  >> /etc/network/interfaces
echo "auto lo" >> /etc/network/interfaces
echo "iface lo inet loopback" >> /etc/network/interfaces

echo "Pushing Primary Network Interface to /etc/network/interfaces"
echo
echo "# The primary network interface"  >> /etc/network/interfaces
echo "auto eth0" >> /etc/network/interfaces
echo "iface eth0 inet static" >> /etc/network/interfaces
echo "address $ip" >> /etc/network/interfaces
echo "netmask 255.255.255.0" >> /etc/network/interfaces
echo "network 192.168.0.0" >> /etc/network/interfaces
echo "broadcast 192.168.0.255" >> /etc/network/interfaces
echo "gateway 192.168.0.1" >> /etc/network/interfaces
echo "dns-nameservers 192.168.0.1 8.8.8.8" >> /etc/network/interfaces
echo "dns-domain $domain.com" >> /etc/network/interfaces
echo "dns-search $domain.com" >> /etc/network/interfaces


echo " 				New Entries In:  /etc/network/interfaces -- (Check For Duplicate Enteries)		 	       	"

cat /etc/network/interfaces

echo "Sleep For 10..." || sleep 10

echo "Restarting Network Interfaces"
sudo networkrestart
echo
echo "SUCCESSFULLY PUSHED NETWORK INTERFACES!"
