#!/bin/bash

echo "Do Update, Upgrade, And Dist-Upgrade"
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo do-release-upgrade

sudo apt install ntfs* synaptic nautilus nautilus-scripts-manager gnome-session-flashback  disktype fatcat fatresize scalpel exfat-fuse exfat-utils sleuthkit ntfs-config syslinux-efi partimage ddrutility disktype extlinux gddrescue

sudo apt-get install putty openssh-server samba 

sudo apt-get install git curl aget wget2 

sudo apt-get remove libreoffice* rhythmbox*

sudo apt-get clean

 sudo apt-get autoremove

sudo apt-get update

sudo apt-get update --fix-missing

